server:
  port: 8084

spring:
  application:
    name: gateway-example
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
#        - id: nacos-producer-route
#          uri: lb://nacos-producer
#          predicates:
#            - name: Path
#              args:
#                patterns: [/api/users/**]

#        - id: nacos-producer-shortcut-route
#          uri: lb://nacos-producer
#          predicates:
#            - Path=/api/users/**

       - id: nacos-producer-custom-route
         uri: lb://nacos-producer
         predicates:
           - PathPrefix=/api
         filters:
           - AddRequestHeader=customToken, waston
