server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    tomcat:
      initial-size: 5
      max-active: 100
      min-idle: 5
      # 获取连接时要不要对该连接进行有效性校验
      test-on-borrow: false
      # 归还连接时要不要对该连接进行有效性校验
      test-on-return: false
      # 是否需要检查空闲的连接有效性
      test-while-idle: true
      # 用来检测连接是否有效的sql
      validation-query: select 1
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 一个连接在池中最小生存的时间, 单位是毫秒
      min-evictable-idle-time-millis: 600000
  application:
    name: sentinel-example
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: 127.0.0.1:8888
      datasource:
        # 自定义(datasource是一个Map, 因此key是自定义的)
        flow-config:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            group-id: SENTINEL_GROUP
            data-id: sentinel-flow-rules.json
            data-type: json
            # 流控规则(见枚举类RuleType)
            rule-type: FLOW
feign:
  sentinel:
    enabled: true
